# Generated by Django 4.2.2 on 2024-03-21 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Data',
            fields=[
                ('Name', models.CharField(default=None, max_length=30)),
                ('username', models.CharField(default=None, max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(default=None, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chatname', models.CharField(default=None, max_length=30)),
                ('Question', models.TextField(default=None, max_length=10000)),
                ('Answer', models.TextField(default=None, max_length=10000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('User', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.user_data')),
            ],
        ),
    ]
